// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type FaqDocumentDataSlicesSlice = QuestionAnswerSlice

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * Slice Zone field in *FAQ*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice> /**
   * Meta Title field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<FaqDocumentData>,
  'faq',
  Lang
>

type FeaturedCreatorsDocumentDataSlicesSlice = FeaturedCreatorSlice

/**
 * Content for Featured Creators documents
 */
interface FeaturedCreatorsDocumentData {
  /**
   * Slice Zone field in *Featured Creators*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_creators.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FeaturedCreatorsDocumentDataSlicesSlice> /**
   * Meta Description field in *Featured Creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: featured_creators.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Featured Creators*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_creators.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Featured Creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: featured_creators.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Featured Creators document from Prismic
 *
 * - **API ID**: `featured_creators`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeaturedCreatorsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FeaturedCreatorsDocumentData>,
    'featured_creators',
    Lang
  >

type LovedCreatorsDocumentDataSlicesSlice = LovedCreatorSlice

/**
 * Content for Loved Creators documents
 */
interface LovedCreatorsDocumentData {
  /**
   * Slice Zone field in *Loved Creators*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: loved_creators.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LovedCreatorsDocumentDataSlicesSlice> /**
   * Meta Description field in *Loved Creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: loved_creators.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Loved Creators*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: loved_creators.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Loved Creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: loved_creators.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Loved Creators document from Prismic
 *
 * - **API ID**: `loved_creators`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LovedCreatorsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LovedCreatorsDocumentData>,
    'loved_creators',
    Lang
  >

type PrivacyPolicyDocumentDataSlicesSlice = never

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * Content field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Slice Zone field in *Privacy Policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice> /**
   * Meta Title field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy_policy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy_policy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    'privacy_policy',
    Lang
  >

type TrustedClientsDocumentDataSlicesSlice = TrustedClientSlice

/**
 * Content for Trusted Clients documents
 */
interface TrustedClientsDocumentData {
  /**
   * Slice Zone field in *Trusted Clients*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: trusted_clients.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TrustedClientsDocumentDataSlicesSlice> /**
   * Meta Description field in *Trusted Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: trusted_clients.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Trusted Clients*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trusted_clients.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Trusted Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: trusted_clients.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Trusted Clients document from Prismic
 *
 * - **API ID**: `trusted_clients`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TrustedClientsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TrustedClientsDocumentData>,
    'trusted_clients',
    Lang
  >

type UsersTermsOfServiceDocumentDataSlicesSlice = never

/**
 * Content for Users Terms of Service documents
 */
interface UsersTermsOfServiceDocumentData {
  /**
   * General TOS field in *Users Terms of Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: users_terms_of_service.general_tos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  general_tos: prismic.RichTextField

  /**
   * Creator TOS field in *Users Terms of Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: users_terms_of_service.creator_tos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  creator_tos: prismic.RichTextField

  /**
   * Developer TOS field in *Users Terms of Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: users_terms_of_service.developer_tos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  developer_tos: prismic.RichTextField

  /**
   * Agency TOS field in *Users Terms of Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: users_terms_of_service.agency_tos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  agency_tos: prismic.RichTextField

  /**
   * Slice Zone field in *Users Terms of Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: users_terms_of_service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UsersTermsOfServiceDocumentDataSlicesSlice> /**
   * Meta Title field in *Users Terms of Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: users_terms_of_service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Users Terms of Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: users_terms_of_service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField
}

/**
 * Users Terms of Service document from Prismic
 *
 * - **API ID**: `users_terms_of_service`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UsersTermsOfServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<UsersTermsOfServiceDocumentData>,
    'users_terms_of_service',
    Lang
  >

export type AllDocumentTypes =
  | FaqDocument
  | FeaturedCreatorsDocument
  | LovedCreatorsDocument
  | PrivacyPolicyDocument
  | TrustedClientsDocument
  | UsersTermsOfServiceDocument

/**
 * Primary content in *FeaturedCreator → Primary*
 */
export interface FeaturedCreatorSliceDefaultPrimary {
  /**
   * Platform Username field in *FeaturedCreator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_creator.primary.platformUsername
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platformUsername: prismic.KeyTextField

  /**
   * Platform Name field in *FeaturedCreator → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_creator.primary.platform_name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform_name: prismic.SelectField<
    'youtubeVideo' | 'youtubeShort' | 'tiktokVideo' | 'freshcutVideo'
  >
}

/**
 * Default variation for FeaturedCreator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedCreatorSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeaturedCreatorSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FeaturedCreator*
 */
type FeaturedCreatorSliceVariation = FeaturedCreatorSliceDefault

/**
 * FeaturedCreator Shared Slice
 *
 * - **API ID**: `featured_creator`
 * - **Description**: FeaturedCreator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedCreatorSlice = prismic.SharedSlice<
  'featured_creator',
  FeaturedCreatorSliceVariation
>

/**
 * Primary content in *LovedCreator → Primary*
 */
export interface LovedCreatorSliceDefaultPrimary {
  /**
   * Platform Username field in *LovedCreator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loved_creators.primary.platform_username
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform_username: prismic.KeyTextField

  /**
   * Platform Name field in *LovedCreator → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: loved_creators.primary.platform_name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform_name: prismic.SelectField<
    'youtubeVideo' | 'youtubeShort' | 'tiktokVideo' | 'freshcutVideo'
  >
}

/**
 * Default variation for LovedCreator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LovedCreatorSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LovedCreatorSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *LovedCreator*
 */
type LovedCreatorSliceVariation = LovedCreatorSliceDefault

/**
 * LovedCreator Shared Slice
 *
 * - **API ID**: `loved_creators`
 * - **Description**: LovedCreator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LovedCreatorSlice = prismic.SharedSlice<
  'loved_creators',
  LovedCreatorSliceVariation
>

/**
 * Primary content in *QuestionAnswer → Primary*
 */
export interface QuestionAnswerSliceDefaultPrimary {
  /**
   * Question field in *QuestionAnswer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_answer.primary.question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField

  /**
   * Answer field in *QuestionAnswer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_answer.primary.answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField

  /**
   * Category field in *QuestionAnswer → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: general
   * - **API ID Path**: question_answer.primary.category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<'general' | 'creatorAgency' | 'support', 'filled'>
}

/**
 * Default variation for QuestionAnswer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionAnswerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<QuestionAnswerSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *QuestionAnswer*
 */
type QuestionAnswerSliceVariation = QuestionAnswerSliceDefault

/**
 * QuestionAnswer Shared Slice
 *
 * - **API ID**: `question_answer`
 * - **Description**: QuestionAnswer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionAnswerSlice = prismic.SharedSlice<
  'question_answer',
  QuestionAnswerSliceVariation
>

/**
 * Primary content in *TrustedClient → Primary*
 */
export interface TrustedClientSliceDefaultPrimary {
  /**
   * Name field in *TrustedClient → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trusted_client.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * logo field in *TrustedClient → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trusted_client.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>
}

/**
 * Default variation for TrustedClient Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrustedClientSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TrustedClientSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *TrustedClient*
 */
type TrustedClientSliceVariation = TrustedClientSliceDefault

/**
 * TrustedClient Shared Slice
 *
 * - **API ID**: `trusted_client`
 * - **Description**: TrustedClient
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrustedClientSlice = prismic.SharedSlice<
  'trusted_client',
  TrustedClientSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataSlicesSlice,
      FeaturedCreatorsDocument,
      FeaturedCreatorsDocumentData,
      FeaturedCreatorsDocumentDataSlicesSlice,
      LovedCreatorsDocument,
      LovedCreatorsDocumentData,
      LovedCreatorsDocumentDataSlicesSlice,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicyDocumentDataSlicesSlice,
      TrustedClientsDocument,
      TrustedClientsDocumentData,
      TrustedClientsDocumentDataSlicesSlice,
      UsersTermsOfServiceDocument,
      UsersTermsOfServiceDocumentData,
      UsersTermsOfServiceDocumentDataSlicesSlice,
      AllDocumentTypes,
      FeaturedCreatorSlice,
      FeaturedCreatorSliceDefaultPrimary,
      FeaturedCreatorSliceVariation,
      FeaturedCreatorSliceDefault,
      LovedCreatorSlice,
      LovedCreatorSliceDefaultPrimary,
      LovedCreatorSliceVariation,
      LovedCreatorSliceDefault,
      QuestionAnswerSlice,
      QuestionAnswerSliceDefaultPrimary,
      QuestionAnswerSliceVariation,
      QuestionAnswerSliceDefault,
      TrustedClientSlice,
      TrustedClientSliceDefaultPrimary,
      TrustedClientSliceVariation,
      TrustedClientSliceDefault,
    }
  }
}
