// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type StandardDocumentDataSlicesSlice = RootPageSlice

/**
 * Content for Standard documents
 */
interface StandardDocumentData {
  /**
   * Slice Zone field in *Standard*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: standard.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StandardDocumentDataSlicesSlice> /**
   * Meta Title field in *Standard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: standard.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Standard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: standard.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Standard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: standard.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Standard document from Prismic
 *
 * - **API ID**: `standard`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StandardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<StandardDocumentData>, 'standard', Lang>

export type AllDocumentTypes = StandardDocument

/**
 * Primary content in *StandardPageContent → Default → Primary*
 */
export interface RootPageSliceDefaultPrimary {
  /**
   * Body field in *StandardPageContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Body
   * - **API ID Path**: standard_page.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField
}

/**
 * Default variation for StandardPageContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RootPageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RootPageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *StandardPageContent*
 */
type RootPageSliceVariation = RootPageSliceDefault

/**
 * StandardPageContent Shared Slice
 *
 * - **API ID**: `standard_page`
 * - **Description**: RootPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RootPageSlice = prismic.SharedSlice<'standard_page', RootPageSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      StandardDocument,
      StandardDocumentData,
      StandardDocumentDataSlicesSlice,
      AllDocumentTypes,
      RootPageSlice,
      RootPageSliceDefaultPrimary,
      RootPageSliceVariation,
      RootPageSliceDefault,
    }
  }
}
