//https://storybook.js.org/docs/react/writing-docs/docs-page
import React from 'react'
import AsyncTester from '@useweb/async-tester'

import getYoutubeChannelDataFromOauth, {
  type GetYoutubeChannelDataFromOauthProps,
  type GetYoutubeChannelDataFromOauthReturn,
} from '../getYoutubeChannelDataFromOauth.js'
import VerifyYoutubeAccountButton from '../../../../../VerifyYoutubeAccount/ui/VerifyYoutubeAccountButton.js'

const defaultArgs: GetYoutubeChannelDataFromOauthProps = {
  // access token generated by VerifyYoutubeAccountButton
  accessToken: '',
}

export default {
  title:
    'lib/integrations/Google/Youtube/utils/getYoutubeChannelData/utils/Get Youtube Channel Data From Oauth',
  args: defaultArgs,
  parameters: {
    signInAs: 'creator1',
  },
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const Template = (args: typeof defaultArgs) => {
  const fn = async (triggerProps = {}) => {
    return await getYoutubeChannelDataFromOauth({ ...args, ...triggerProps })
  }

  return (
    <>
      <AsyncTester<
        GetYoutubeChannelDataFromOauthReturn,
        GetYoutubeChannelDataFromOauthProps
      >
        fn={fn}
        triggerComponent={() => (
          <>
            <VerifyYoutubeAccountButton isVerified={false} />
          </>
        )}
      />
    </>
  )
}

export const Default = {
  render: (args: GetYoutubeChannelDataFromOauthProps) => {
    return <Template {...args} />
  },
}

// export const Variant = {
//  ...Default,
//  args: {
//  ...defaultArgs,
// } satisfies GetYoutubeChannelDataFromOauthProps
// }
